config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get'top' => 'homes#top'#resourcesメソッドに書き換える
  patch 'books/:id' => 'books#update', as: 'update_book'#resourcesメソッドで対応できない？
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'#resourcesメソッドで対応できない？
  root to: "homes#top"
  resources :books

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new #この記述いらない？？
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save#saveは新しいデータに対して有効。updateでは使えない
       flash[:notice] = "Book was successfully created."
       redirect_to book_path(@book.id)
    else
      @books = Book.all
      flash.now[:alert] = "投稿が失敗しました。"
      render :index
    end  
  end

  def show #詳細画面。投稿押したら飛んでくる画面
    @book = Book.find(params[:id])
    # redirect_to '/books'
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      flash.now[:alert] = "編集が失敗しました。"
      render :edit 
    end  
  end
  
  def destroy #destroyしたらbooks一覧画面にリンクように
    book = Book.find(params[:id])
    book.destroy
    redirect_to'/books'
  end
  # ここから先は保存機能と同時期に書いてる
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<head>
  <link rel="stylesheet" href="show_1.scss" />
</head>

<body>
<h2>Editing Book</h2>
<%= flash[:alert] %>
</p>

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>
<div class="field">
  <p>Title</p>
  <%= f.text_field :title %>
</div>

<div class="field">
  <p>Body</p>
  <%= f.text_area :body %>
</div>

  <%= f.submit 'Update Book' %>

<% end %>

<%=link_to "Show", book_path(@book.id) %> |

<%=link_to "Back", '/books' %>
</body>

app/views/books/index.html.erb
<head>
  <!--<link rel="stylesheet" href="index_1.scss" />-->
</head>

<body>
<p id="notice"></p>
<h1>Books</h1>
<!--<table>-->
<% @books.each do |book| %>
<table>
  <thead class="title-box">
    <tr>
     <th class="book-title">Title</th>
     <th class="book-title-body">Body</th>
   </tr>
  </thead>
    <span>
      <%= book.title %>
    </span>

    <span>
      <%= book.body %>
    </span>
    <span>
      <%=link_to "Show", book_path(book.id) %>
    </span>
    <span>
      <%= link_to "Edit", edit_book_path(book.id) %>
    <span>
      <%=  link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are yuo sure？" %>
    </span>
<% end %>
</table>

<div class="New-book">
<h2>New book</h2>
<%= flash[:alert] %>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @book do |f| %>
  <p>Title</p><!--検証では<label for="book_title">Title</label>-->
  <%= f.text_field :title %>
  <p>Body</p><!--検証では<label for="book_title">Body</label>-->
  <%= f.text_area :body %>
 <div>
  <%= f.submit 'Create Book' %><!--送信ボタンはBodyの下に来ている-->
 </div>
<% end %>
</div>
</body>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<head>
  <link rel="stylesheet" href="show_1.scss" />
</head>

<body>
 <%= flash[:notice] %>
 <p id="notice"></p>
 <div class="title">
  <p>
   <strong>Title:</strong>
    <%= @book.title %>
  </p>
 </div>

<div class="body">
 <p>
  <strong>Body:</strong>
   <%= @book.body %>
 </p>
</div>

<div class="link">
 <%= link_to "Edit", edit_book_path(@book.id) %> |
 <%= link_to "Back", '/books' %>
</div>
</body>

app/views/homes/top.html.erb
<header>
 <h1>ようこそ 
 <strong>Bookers</strong>
 へ！</h1>
</header>

<div class="top_text">
<p><strong>Bookers</strong> 
では、さまざまな書籍に関するあなたの意見や</p>
<br>

<p>印象を共有し交換することができます</p>
</div>

<div class="to_index">
<%=link_to "start", '/books' %>
</div>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers 課題</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>